services:
  - type: web
    name: pocplaywright-backend
    runtime: image
    repo: https://github.com/im250102/POCPlaywright
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__MongoDb
        value: mongodb+srv://ignaciomartin1083_db_user:rkODcehQ9TPm5cCs@nachoia.km2bzbn.mongodb.net/?appName=NachoIA
    
      - key: DatabaseName
        value: POCPlaywright
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        value: POCPlaywright
      - key: Jwt__Audience
        value: POCPlaywright
      - key: Jwt__TokenExpiryMinutes
        value: 60
